### PR TITLE
Add sessions track

### PR DESCRIPTION
**Pull request by halkeye**
@jrudio I found out sessions has Tracks when audio is being played, so quickly added it based on my own return values.

Do you have any tests? I can provide a sample file

### CODE REVIEW

**Comment by jrudio** [comment]
@halkeye Thanks, for the find and the pull request!

Admittedly, I haven't ventured into testing with Go. Can you point me in the direction for testing? Or how to test?

**Comment by halkeye** [comment]
I'm very new to go myself.

I know they have a built in testing library. You can just do "go test" in the directory

https://golang.org/pkg/testing/

**Comment by jrudio** [comment]
Thanks, it seems pretty straightforward. I can't do it tonight, but should
be able to get a simple test of sessions going sometime tomorrow.

**Comment by jrudio** [comment]
@halkeye 

Ok, added a test, and it's using sample data from two sessions: one video, and one audio(music).

If you have different sample data can you please test it under `plex_test.go`?

776a2a02def9255d89942343446101a2fd191b54

**Comment by halkeye** [comment]
Nope, that looks pretty much like mine. Thanks!

**Pull request merged**
