### PR TITLE
Add GetInvitedFriends, RemoveInvitedFriend client functions

### PR DESCRIPTION
**Pull request by mooseburgr**
closes https://github.com/jrudio/go-plex-client/issues/46

### CODE REVIEW

**Comment by mooseburgr** [comment]
FWIW, this is working in "prod" as well as via local ad-hoc tests:
https://github.com/mooseburgr/plex-utils/commit/4d0295dbce1de25097e7c073fbf9e00420a67fd7
https://plexy.vercel.app/

I wasn't sure what kind of tests you'd like, so I only added some minimal unit tests vs committing any integration tests. If the OS env variables are expected to work, I can definitely add back my integ tests, lmk!

**Comment by jrudio** [comment]
Hey @mooseburgr, thanks for the PR. I looked it over and so far it reads well. 

I am going to test manually. As for unit and integration test, I am still trying to figure out best practice for integration testing a client against an API. Any chance you have pointers or know of an example repository that does this? 

I feel like if a unit tests passes with example data, but integration fails because PMS changed an endpoint response, why not just stick with an integration test? 😞 Maybe that's a bad thought process

To your question about OS env vars, master branch doesn't utilize those variables, but `feature/cloud-build` branch https://github.com/jrudio/go-plex-client/blob/be9ebdfdd4182cd0571fa9556ba9d17a95a8f46f/plex_test.go#L20 does, which I plan to work on... soon.

So if you do not want to commit those, that is fine.

**Comment by mooseburgr** [comment]
Ha nope, I totally agree! Mocking out any sort of actual response from the server is pretty useless for client SDK stuff like this, imo. Other than maybe de/serialization testing.

Ugh, I feel like maybe spinning up a disposable / test server via Docker would meet that need, but I have yet to try it. Plus that then requires Docker available on whatever device is running the integ tests, but that's not too terrible. I might play around with it locally at some point and throw something up, but no guarantees.

Otherwise I might poke around what you're doing in the `cloud-build` branch and see if there's something there I could help with in terms of setting up integ tests. 🤷

**Comment by jrudio** [comment]
Sorry for the delay, just ran the pr manually and works fine for me.

Going to merge now!

**Comment by mooseburgr** [comment]
oh no problem! just happened to check in and noticed it was behind your master branch

**Comment by mooseburgr** [comment]
thank you so much!

**Pull request merged**
