### PR TITLE
fixed the types for metadata json responses

### LINKED ISSUE #32: GetSessions() - Fix metadata types
Do not use metadatav1, and fix types on metadata

### PR DESCRIPTION
**Pull request by jrudio**
With PMS 1.24.4.5081, the types that were changed should work for fetching sessions.

This will close #32

### CODE REVIEW

**Comment by danopia** [comment]
Hi, I had the type issue with `GetSessions()` as well, and switching to this branch with `go get github.com/jrudio/go-plex-client@dfd65db5fe92762d7f1b922b4c230fb6dd63fd5e` fixed my issue. LGTM

**Comment by jrudio** [comment]
@danopia thanks for confirming these changes for `GetSessions()`. It seems these changes break `GetPlaylist()` (see #41) and possibly others.

**Comment by danopia** [comment]
I actually observed an additional break on `GetSessions()` when running the above githash:

```
json: cannot unmarshal string into Go struct field Media.MediaContainer.Metadata.Media.aspectRatio of type float32
```

I don't have a capture of the JSON yet, so I'll be watching for it, seems to be related to a smarttv

**Comment by danopia** [comment]
I grabbed a snapshot of a payload that mistypes `aspectRatio`, here's a copy with all IDs replaced: https://gist.github.com/danopia/40582119a310f4291fa001397179142c

On first glance it seems to be the only field that doesn't line up with the structs.

Would it be at all practical to allow decoding strings into number fields and vice-versa? It seems nothing prevents Plex from making another "small" change like this in the future :(

**Comment by jrudio** [comment]
Latest push handles the bool or int found in the optimizedForStreaming field in the response JSON from PMS

Will wait a bit to merge

**Comment by raine** [comment]
Could this be merged?

```
query = http://raspi:32400/library/sections/7/all
panic: json: cannot unmarshal number into Go struct field Media.MediaContainer.Metadata.Media.optimizedForStreaming of type bool
```

**Comment by jrudio** [comment]
Sorry I think at the time I was waiting on a PR from one of the commenters on one of the issues on this repo because their fork looked good. 

I merged it but there is improvements to be made.

**Pull request merged**
